function fearAnalysesReactPipeline(rootDir,sessionName,varargin)
load(fullfile(rootDir,sessionName,[sessionName '.basicMetaData.mat']))    

reAnalyses=false;
for idx=1:length(varargin)/2
    varName=varargin{2*idx-1};
    varVal=varargin{2*idx};

    switch lower(varName)
        case lower('reAnalyses')
            reAnalyses=varVal;
        otherwise
            warning(['wrong option name : ' varName])
            return                
    end
end


%% ICA based reactivation
if reAnalyses || ~exist([basicMetaData.AnalysesName '-icaReac.mat'],'file')
    fear_icaReac(basicMetaData.Basename)
end

%%
if reAnalyses || ~exist([basicMetaData.AnalysesName '-instReacInfo.mat'],'file') ...
              || ~exist([basicMetaData.AnalysesName '-icaReacInfo.mat'],'file') 
    fear_separate_reactInfo(basicMetaData.Basename)
end
%% SWR/spindle/HFO triggered ica reactivation
% SWR triggered, short bin (20ms)
if (redoInstReac||reAnalyses || ~exist([basicMetaData.AnalysesName '-swrTrigIcaReac.mat'],'file'))&&...
        exist([basicMetaData.Basename '.ripples.events.mat'],'file')&&...
        exist([basicMetaData.Basename '.pfcSpindle.events.mat'],'file')
    fear_swrTrigIcaReac(basicMetaData.Basename)
end
if (redoInstReac||reAnalyses || ~exist([basicMetaData.AnalysesName '-spdlTrigIcaReac.mat'],'file'))
    fear_spdlTrigIcaReac(basicMetaData.Basename)
end

if (redoInstReac||reAnalyses || ~exist([basicMetaData.AnalysesName '-hfoTrigIcaReac.mat'],'file'))&&...
        exist([basicMetaData.Basename '.amyHFO.events.mat'],'file')
    fear_hfoTrigIcaReac(basicMetaData.Basename)
end
%% exclude around delta
% if reAnalyses || ~exist([basicMetaData.AnalysesName '-icaReacCCG_exDelta.mat'],'file')
%     fear_icaReac_CCG_exDelta(basicMetaData.Basename)
% end
% if reAnalyses || ~exist([basicMetaData.AnalysesName '-icaReacCCG_exAmySpdl.mat'],'file')    
%     fear_icaReac_CCG_exAmySpdl(basicMetaData.Basename)
% end
%%
% % do shuffling for CCG (to save time, use GPU)
%
% shuffle_icaReacCCG
% shuffle_icaReacCCG_chamber
% shuffle_icaReacCCG_exSWR
%% add znccg (zero-normalized ccg)
if  reAnalyses ||...
        (exist([basicMetaData.AnalysesName '-icaReacCCG_sh.mat'],'file') && ~exist([basicMetaData.AnalysesName '-icaReacZNCCG.mat'],'file'))
    fear_addZNCCGtoReacCCG(basicMetaData.Basename,...
        'ccgFile','-icaReacCCG_sh.mat',...
        'reacFile','-icaReac.mat',...
        'reacName','icaReac',...
        'varName','icaReacCCG_sh',...
        'saveFile','-icaReacZNCCG.mat',...
        'saveVarName','icaReacZNCCG'...
        );
end

if  reAnalyses || ...
        (exist([basicMetaData.AnalysesName '-icaReacCCG_exSWR_sh.mat'],'file') && ~exist([basicMetaData.AnalysesName '-icaReacZNCCG_exSWR.mat'],'file'))
    fear_addZNCCGtoReacCCG_exSWR(basicMetaData.Basename,...
        'ccgFile','-icaReacCCG_exSWR_sh.mat',...
        'reacFile','-icaReac.mat',...
        'reacName','icaReac',...
        'varName','icaReacCCG_exSWR_sh',...
        'saveFile','-icaReacZNCCG_exSWR.mat',...
        'saveVarName','icaReacZNCCG_exSWR'...
        );
end

if  reAnalyses || ...
        (exist([basicMetaData.AnalysesName '-icaReacCCGchamber_sh.mat'],'file') && ~exist([basicMetaData.AnalysesName '-icaReacZNCCGchamber.mat'],'file'))
    fear_addZNCCGtoReacCCGchamber(basicMetaData.Basename,...
        'ccgFile','-icaReacCCGchamber_sh.mat',...
        'reacFile','-icaReac.mat',...
        'reacName','icaReac',...
        'varName','icaReacCCGchamber_sh',...
        'saveFile','-icaReacZNCCGchamber.mat',...
        'saveVarName','icaReacZNCCGchamber'...
        );
end

if  reAnalyses || ...
        (exist([basicMetaData.AnalysesName '-icaReacCCGchamberCue_sh.mat'],'file') && ~exist([basicMetaData.AnalysesName '-icaReacZNCCGchamberCue.mat'],'file'))
    fear_addZNCCGtoReacCCGchamberCue(basicMetaData.Basename,...
        'ccgFile','-icaReacCCGchamberCue_sh.mat',...
        'reacFile','-icaReac.mat',...
        'reacName','icaReac',...
        'varName','icaReacCCGchamberCue_sh',...
        'saveFile','-icaReacZNCCGchamberCue.mat',...
        'saveVarName','icaReacZNCCGchamberCue'...
        );
end

if reAnalyses || ...
        (exist([basicMetaData.AnalysesName '-icaReacCCG_exHFObaseCond_sh.mat'],'file') && ~exist([basicMetaData.AnalysesName '-icaReacZNCCG_exHFObaseCond.mat'],'file'))
    fear_addZNCCGtoReacCCG_exHFObaseCond(basicMetaData.Basename,...
        'ccgFile','-icaReacCCG_exHFObaseCond_sh.mat',...
        'reacFile','-icaReac.mat',...
        'reacName','icaReac',...
        'varName','icaReacCCG_exHFObaseCond_sh',...
        'saveFile','-icaReacZNCCG_exHFObaseCond.mat',...
        'saveVarName','icaReacZNCCG_exHFObaseCond'...
        );
end

%%
%% peak significance test on reac CCG (PCA/ICA)
if reAnalyses || ...
        ~exist([basicMetaData.AnalysesName '-instReacCCG_sig.mat'],'file') ||...
        ~exist([basicMetaData.AnalysesName '-icaReacCCG_sig.mat'],'file') ||...
        (exist([basicMetaData.Basename '.ripples.events.mat'],'file')&& ~exist([basicMetaData.AnalysesName '-instReacCCG_exSWR_sig.mat'],'file') )||...
        (exist([basicMetaData.Basename '.ripples.events.mat'],'file')&& ~exist([basicMetaData.AnalysesName '-icaReacCCG_exSWR_sig.mat'],'file'))||...
        ~exist([basicMetaData.AnalysesName '-instReacZNCCG_sig.mat'],'file') ||...
        ~exist([basicMetaData.AnalysesName '-icaReacZNCCG_sig.mat'],'file') ||...
        (exist([basicMetaData.Basename '.ripples.events.mat'],'file')&& ~exist([basicMetaData.AnalysesName '-instReacZNCCG_exSWR_sig.mat'],'file') )||...
        (exist([basicMetaData.Basename '.ripples.events.mat'],'file')&& ~exist([basicMetaData.AnalysesName '-icaReacZNCCG_exSWR_sig.mat'],'file')) ||...
        ~exist([basicMetaData.AnalysesName '-instReacCCGchamber_sig.mat'],'file') ||...
        ~exist([basicMetaData.AnalysesName '-instReacZNCCGchamber_sig.mat'],'file') ||...
        ~exist([basicMetaData.AnalysesName '-icaReacCCGchamber_sig.mat'],'file') ||...
        ~exist([basicMetaData.AnalysesName '-icaReacZNCCGchamber_sig.mat'],'file')||...
        ~exist([basicMetaData.AnalysesName '-instReacZNCCG_exKcomplex_sig.mat'],'file') ||...
        ~exist([basicMetaData.AnalysesName '-icaReacZNCCG_exKcomplex_sig.mat'],'file') ||...
        ~exist([basicMetaData.AnalysesName '-instReacCCG_exKcomplex_sig.mat'],'file') ||...
        ~exist([basicMetaData.AnalysesName '-icaReacCCG_exKcomplex_sig.mat'],'file') ||...
        ~exist([basicMetaData.AnalysesName '-instReacZNCCGchamberCue_sig.mat'],'file') ||...
        ~exist([basicMetaData.AnalysesName '-icaReacZNCCGchamberCue_sig.mat'],'file') ||...
        ~exist([basicMetaData.AnalysesName '-icaReacZNCCG_exHFObaseCond_sig.mat'],'file')
     fear_testSignificance_reacCCG(basicMetaData.Basename)
end

%% get coactivation partners
if reAnalyses || ~exist([basicMetaData.AnalysesName '-instReacPartner.mat'],'file') || ...
        ~exist([basicMetaData.AnalysesName '-icaReacPartner.mat'],'file')

    fear_coactPartner(basicMetaData.Basename)
end

%% get timestamps of coactivation of ica Reac

if (reAnalyses || ~exist([basicMetaData.AnalysesName '-icaCoactTimeHT.mat'],'file') )&&...
        exist(basicMetaData.lfp,'file')
    
    fear_getIcaCoactTimeHighThreshold(basicMetaData.Basename)
end

if (reAnalyses || ~exist([basicMetaData.AnalysesName '-icaCoactTimeCondHT.mat'],'file')) &&...
        exist(basicMetaData.lfp,'file')
    
    fear_getIcaCoactTimeCondHighThreshold(basicMetaData.Basename)
end


%% ica coactivation triggered LFP average

if (reAnalyses || ~exist([basicMetaData.AnalysesName '-icaCoactTrigLFPHT.mat'],'file') ) &&...
        exist([basicMetaData.AnalysesName '-icaCoactTimeHT.mat'],'file')  &&...
        exist(basicMetaData.lfp,'file')
    
    fear_icaCoactTrigLFPaverageHIghThreshold(basicMetaData.Basename)
end

%% coact trig wavelet

if (reAnalyses ||...
        ~exist([basicMetaData.AnalysesName '-instCoactTrigWaveletHT.mat'],'file') ||...
        ~exist([basicMetaData.AnalysesName '-icaCoactTrigWaveletHT.mat'],'file')) &&...
        exist(basicMetaData.lfp,'file')
    
    fear_coactTrigWaveletHighThreshold(basicMetaData.Basename);
end

if (reAnalyses ||...
        ~exist([basicMetaData.AnalysesName '-icaCoactTrigWaveletCueRet.mat'],'file') )  &&...
        exist(basicMetaData.lfp,'file')
    fear_icaCoactTrigWaveletCueRet(basicMetaData.Basename);
end
%% event triger coactivation

if (reAnalyses || ~exist([basicMetaData.AnalysesName '-evtTrigIcaReactHT.mat'],'file') ) 
fear_evtTrigReact(basicMetaData.Basename,...
    'targetHC',3,...
	'behavior','nrem',...
    'varName','evtTrigIcaReact',...
    'saveFile',[basicMetaData.AnalysesName '-evtTrigIcaReactHT.mat'],...
    'reacFile',[basicMetaData.AnalysesName '-icaCoactTimeCondHT.mat'])
end


if (reAnalyses || ~exist([basicMetaData.AnalysesName '-evtTrigIcaReactChamber.mat'],'file') ) 
    fear_evtTrigReactChamber(basicMetaData.Basename,...
        'varName','evtTrigIcaReact',...
        'saveFile',[basicMetaData.AnalysesName '-evtTrigIcaReactChamber.mat'],...
        'reacFile',[basicMetaData.AnalysesName '-icaCoactTimeCondHT.mat'])
end


if (reAnalyses || ~exist([basicMetaData.AnalysesName '-shockTrigIcaReact.mat'],'file') ) 
    fear_shockTrigReact(basicMetaData.Basename,...
        'varName','shockTrigIcaReact',...
        'saveFile',[basicMetaData.AnalysesName '-shockTrigIcaReact.mat'],...
        'reacFile',[basicMetaData.AnalysesName '-icaReacTimeCond.mat'])
end

if (reAnalyses || ~exist([basicMetaData.AnalysesName '-shockTrigIcaCoact.mat'],'file') ) 
    fear_shockTrigCoact(basicMetaData.Basename,...
        'varName','shockTrigIcaCoact',...
        'saveFile',[basicMetaData.AnalysesName '-shockTrigIcaCoact.mat'],...
        'reacFile',[basicMetaData.AnalysesName '-icaCoactTimeCondHT.mat'])
end

%% HFO triggered reactivation
if (reAnalyses || ~exist([basicMetaData.AnalysesName '-amyHFOtrigIcaCoact.mat'],'file') ) 
    fear_amyHFOtrigReact(basicMetaData.Basename,...
        'varName','gammaTrigIcaCoact',...
        'saveFile',[basicMetaData.AnalysesName '-amyHFOtrigIcaCoact.mat'],...
        'reacFile',[basicMetaData.AnalysesName '-icaCoactTimeCondHT.mat'])
end


%% event/gamma triggered coactivation
if  (reAnalyses || ~exist([basicMetaData.AnalysesName '-evtTrigIcaCoact-cueRet.mat'],'file') ||...
                   ~exist([basicMetaData.AnalysesName '-evtTrigIcaCoact-postNREM.mat'],'file') )
    fear_evtTrigIcaCoactStrength(basicMetaData.Basename)               
end

if  (reAnalyses || ~exist([basicMetaData.AnalysesName '-gammaTrigIcaCoact-cueRet.mat'],'file') ||...
                   ~exist([basicMetaData.AnalysesName '-gammaTrigIcaCoact-postNREM.mat'],'file') ) &&...
       exist([basicMetaData.Basename '.pfcGamma.events.mat'],'file') &&...
       exist([basicMetaData.Basename '.pfcLowGamma.events.mat'],'file') &&...
       exist([basicMetaData.Basename '.pfcHighGamma.events.mat'],'file')  
    fear_gammaTrigIcaCoactStrength(basicMetaData.Basename)               
end

if  (reAnalyses || ~exist([basicMetaData.AnalysesName '-amyGammaTrigCoact-cueRet.mat'],'file') ||...
                   ~exist([basicMetaData.AnalysesName '-amyGammaTrigCoact-postNREM.mat'],'file') ) &&...
       exist([basicMetaData.Basename '.amyLowGamma.events.mat'],'file')
    fear_amyGammaTrigIcaCoactStrength(basicMetaData.Basename)               
end
%%
if reAnalyses || ~exist([basicMetaData.AnalysesName '-coactCompCell.mat'],'file')
    fear_coactCompCell(basicMetaData.Basename)
end

%%
if reAnalyses || ~exist([basicMetaData.AnalysesName '-icaReacCCG_exHFO.mat'],'file')
    fear_icaReac_CCG_exHFO(basicMetaData.Basename)
end




